// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// TO CONFIGURE FIREBASE:
/// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
/// 2. Run: flutterfire configure
/// 3. Select your Firebase project and platforms
/// 4. This file will be automatically updated with your configuration
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase configuration
  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38OREm8iIKl1MnWXkcnbmsW4Os2J-zhM',
    appId: '1:263100346509:android:27cad5d624a3a6cb8df2c4',
    messagingSenderId: '263100346509',
    projectId: 'tasky-cbcb4',
    storageBucket: 'tasky-cbcb4.firebasestorage.app',
  );
}
/*

firebase_options.dart
       ↓
يحدد مشروع Firebase
       ↓
initializeApp يستخدمه
       ↓
الاتصال يتم بالمشروع الصحيح

 */